export * from './base.object';
export * from './door.object';
export * from './interactive.object';
export * from './movable.object';
export * from './npc.object';
export * from './other-player.object';
export * from './player.object';
export * from './professor-npc.object';
export * from './trigger.object';
