export enum AUDIO {
  MENU = 'menu',
  SELECT = 'select',
  OVERWORD_MENU_SELECT = 'overworld_menu_select',
  OVERWORD_MENU_DECISION = 'overworld_menu_decision',
  OVERWORD_MENU_CLOSE = 'overworld_menu_close',
  POKEBOX_ACCESS = 'pokebox_access',
  POKEBOX_CLOSE = 'pokebox_close',
  BAG_CATEGORY = 'bag_category',
  BAG_CLOSE = 'bag_close',
  BAG_DECISON = 'bag_decision',
  BAG_SELECT = 'bag_select',
  REGISTER = 'register',
  ITEM_GET = 'item_get',
}
