export enum AUDIO {
  SELECT_0 = 'select_0',
  SELECT_1 = 'select_1',
  SELECT_2 = 'select_2',
  OPEN_0 = 'open_0',
  OPEN_1 = 'open_1',
  CANCEL_0 = 'cancel_0',
  CANCEL_1 = 'cancel_1',
  GET_0 = 'get_0',
  BUY = 'buy',
  JUMP = 'jump',
  REACTION_0 = 'reaction_0',
  THROW = 'throw',
  DOOR_ENTER = 'enter',
  BALL_CATCH = 'ball_catch',
  BALL_DROP = 'ball_drop',
  BALL_ENTER = 'ball_enter',
  BALL_EXIT = 'ball_exit',
  BALL_SHAKE = 'ball_shake',
  BUZZER = 'buzzer',
  REWARD = 'reward',
  SHINY = 'shiny',
  FLEE = 'flee',
  EVOL_INTRO = 'evol_0',
  EVOL = 'evol_1',
  CONG = 'cong',
  HATCH = 'hatch',
}
