export const enum TEXTURE {
  //window
  WINDOW_BAG = "window_bag",
  WINDOW_BAG_O = "window_bag_o",
  WINDOW_SYS = "window_sys",
  WINDOW_MENU = "window_menu",
  WINDOW_MENU_S = "window_menu_s",
  WINDOW_RED = "window_red",
  WINDOW_REWARD = "window_reward",
  WINDOW_0 = "window0",
  WINDOW_1 = "window1",
  WINDOW_2 = "window2",
  WINDOW_3 = "window3",
  WINDOW_4 = "window4",
  WINDOW_5 = "window5",
  WINDOW_6 = "window6",
  WINDOW_7 = "window7",
  WINDOW_8 = "window8",
  WINDOW_9 = "window9",
  WINDOW_10 = "window10",

  //backgrounds
  BG_LOAD = "bg_load",
  BG_TITLE = "bg_title",
  BG_BAG = "bg_bag",
  BG_PC = "bg_pc",
  BG_HM = "bg_hm",
  BG_EVOLVE = "bg_evolve",
  BG_BLACK = "bg_black",

  //maps
  INDOOR_TILE_FLOOR = "indoor_floor",
  INDOOR_TILE_OBJECT = "indoor_object",
  OUTDOOR_TILE_FLOOR = "outdoor_floor",
  OUTDOOR_TILE_EDGE = "outdoor_edge",
  OUTDOOR_TILE_OBJECT = "outdoor_object",
  OUTDOOR_TILE_OBJECT_URBAN = "outdoor_object_urban",
  OUTDOOR_TILE_URBAN = "outdoor_urban",
  OVERWORLD_000 = "overworld-000",
  OVERWORLD_001 = "overworld-001",
  OVERWORLD_002 = "overworld-002",
  OVERWORLD_003 = "overworld-003",
  OVERWORLD_011 = "overworld-011",
  OVERWORLD_021 = "overworld-021",

  //icons
  ICON_PC = "icon_pc",
  ICON_BAG_M = "icon_bag_m",
  ICON_BAG_G = "icon_bag_g",
  ICON_PROFILE = "icon_profile",
  ICON_EXIT = "icon_exit",
  ICON_RUNNING = "icon_running",
  ICON_LOCATION = "icon_location",
  ICON_MONEY = "icon_money",
  ICON_MENU = "icon_menu",
  ICON_OPTION = "icon_option",
  ICON_CANDY = "ICON_candy",
  ICON_SHINY = "icon_shiny",
  ICON_OWNED = "icon_owned",

  //etc
  LOGO_0 = "logo_0",
  LOGO_DISCORD = "logo_discord",
  LOGO_GOOGLE = "logo_google",
  PC_NAME = "pc_name",
  PC_DESC = "pc_desc",
  PC_ARROW = "pc_arrow",
  PC_BALL_001 = "pc_ball_001",
  PC_BALL_002 = "pc_ball_002",
  PC_BALL_003 = "pc_ball_003",
  PC_BALL_004 = "pc_ball_004",
  REWARD = "reward",
  REWARD_OVERLAY_0 = "reward_overlay_0",
  BATTLE_BAR = "battle_bar",
  GENDER_0 = "gender_0",
  GENDER_1 = "gender_1",
  PAUSE_B = "pause_b",
  PAUSE_W = "pause_w",
  SEASON_0 = "season_0",
  SEASON_1 = "season_1",
  SEASON_2 = "season_2",
  SEASON_3 = "season_3",
  OVERWORLD_SHINY = "overworld_shiny",
  BOY_1_STATUE = "boy_1_statue",
  BOY_2_STATUE = "boy_2_statue",
  BOY_3_STATUE = "boy_3_statue",
  BOY_4_STATUE = "boy_4_statue",
  GIRL_1_STATUE = "girl_1_statue",
  GIRL_2_STATUE = "girl_2_statue",
  GIRL_3_STATUE = "girl_3_statue",
  GIRL_4_STATUE = "girl_4_statue",
  BOY_1_MOVEMENT = "boy_1_movement",
  BOY_2_MOVEMENT = "boy_2_movement",
  BOY_3_MOVEMENT = "boy_3_movement",
  BOY_4_MOVEMENT = "boy_4_movement",
  GIRL_1_MOVEMENT = "girl_1_movement",
  GIRL_2_MOVEMENT = "girl_2_movement",
  GIRL_3_MOVEMENT = "girl_3_movement",
  GIRL_4_MOVEMENT = "girl_4_movement",
  BOY_1_RIDE = "boy_1_ride",
  BOY_2_RIDE = "boy_2_ride",
  BOY_3_RIDE = "boy_3_ride",
  BOY_4_RIDE = "boy_4_ride",
  GIRL_1_RIDE = "girl_1_ride",
  GIRL_2_RIDE = "girl_2_ride",
  GIRL_3_RIDE = "girl_3_ride",
  GIRL_4_RIDE = "girl_4_ride",
  BOY_1_HM = "boy_1_hm",
  BOY_2_HM = "boy_2_hm",
  BOY_3_HM = "boy_3_hm",
  BOY_4_HM = "boy_4_hm",
  GIRL_1_HM = "girl_1_hm",
  GIRL_2_HM = "girl_2_hm",
  GIRL_3_HM = "girl_3_hm",
  GIRL_4_HM = "girl_4_hm",
  BOY_1_BACK = "boy_1_back",
  BOY_2_BACK = "boy_2_back",
  BOY_3_BACK = "boy_3_back",
  BOY_4_BACK = "boy_4_back",
  GIRL_1_BACK = "girl_1_back",
  GIRL_2_BACK = "girl_2_back",
  GIRL_3_BACK = "girl_3_back",
  GIRL_4_BACK = "girl_4_back",
  BOY_1_SURF = "boy_1_surf",
  BOY_2_SURF = "boy_2_surf",
  BOY_3_SURF = "boy_3_surf",
  BOY_4_SURF = "boy_4_surf",
  GIRL_1_SURF = "girl_1_surf",
  GIRL_2_SURF = "girl_2_surf",
  GIRL_3_SURF = "girl_3_surf",
  GIRL_4_SURF = "girl_4_surf",
  SURF = "surf",
  PARTICLE_HM_0 = "particle_hm_0",
  PARTICLE_HM_1 = "particle_hm_1",
  PARTICLE_EVOL = "particle_evol",
  BAG_POCKET_BALL = "bag_pocket_ball",
  BAG_POCKET_ETC = "bag_pocket_ETC",
  BAG_POCKET_BERRY = "bag_pocket_berry",
  BAG_POCKET_KEY = "bag_pocket_key",
  BAG_BAR = "bag_bar",
  ARROW_W = "arrow_w",
  ARROW_B = "arrow_b",
  ARROW_G = "arrow_g",
  ARROW_R = "arrow_r",
  FINGER = "finger",
  BLANK = "blank",
  TYPES = "types",
  TYPES_1 = "types_1",
  POKEMON_CALL = "pokemon_call",
  POKEMON_RECALL = "pokemon_recall",
  POKEMON_OVERWORLD = "pokemon_overworld",
  POKEBALL_THROW = "pokeball_throw",
  POKEBALL_GROUND = "pokeball_ground",
  LEGACY_POKEBALL_THROW = "legacy_pokeball_throw",
  OVERWORLD_SHADOW = "overworld_shadow",
  OVERWORLD_SHADOW_WATER = "overworld_shadow_water",
  EXCLMATION = "exclamation",
  BG_OVERLAY_0 = "bg_overlay_0",
  EMO = "emo",
  SPARKLE = "sparkle",
}

export const TEXTURE_PLAYER_MAP: Record<string, TEXTURE> = {
  BOY_1_MOVEMENT: TEXTURE.BOY_1_MOVEMENT,
  BOY_2_MOVEMENT: TEXTURE.BOY_2_MOVEMENT,
  BOY_3_MOVEMENT: TEXTURE.BOY_3_MOVEMENT,
  BOY_4_MOVEMENT: TEXTURE.BOY_4_MOVEMENT,
  GIRL_1_MOVEMENT: TEXTURE.GIRL_1_MOVEMENT,
  GIRL_2_MOVEMENT: TEXTURE.GIRL_2_MOVEMENT,
  GIRL_3_MOVEMENT: TEXTURE.GIRL_3_MOVEMENT,
  GIRL_4_MOVEMENT: TEXTURE.GIRL_4_MOVEMENT,
  BOY_1_RIDE: TEXTURE.BOY_1_RIDE,
  BOY_2_RIDE: TEXTURE.BOY_2_RIDE,
  BOY_3_RIDE: TEXTURE.BOY_3_RIDE,
  BOY_4_RIDE: TEXTURE.BOY_4_RIDE,
  GIRL_1_RIDE: TEXTURE.GIRL_1_RIDE,
  GIRL_2_RIDE: TEXTURE.GIRL_2_RIDE,
  GIRL_3_RIDE: TEXTURE.GIRL_3_RIDE,
  GIRL_4_RIDE: TEXTURE.GIRL_4_RIDE,
};
