export enum UI {
  CONNECT = 'ConnectUi',
  MESSAGE = 'MessageUi',
  LOGIN = 'LoginUi',
  REGISTER = 'RegisterUi',
  TITLE = 'TitleUi',
  WELCOME = 'WelcomeUi',
  NEWGAME = 'NewgameUi',
  ACCOUNT_DELETE = 'AccountDeleteUi',
  CONNECT_ACCOUNT_DELETE = 'ConnectAccountDeleteUi',
  OVERWORLD_HUD = 'OverworldHUDUi',
  OVERWORLD_MENU = 'OverworldMenuUi',
  OVERWORLD_CONNECTING = 'OverworldConnectingUi',
  BAG = 'BagUi',
  BAG_MENU = 'BagMenuUi',
  BAG_REGISTER = 'BagRegisterUi',
  SHOP = 'ShopUi',
  POKEBOX = 'PokeboxUi',
  SAFARI_LIST = 'SafariListUi',
  HIDDEN_MOVE = 'HiddenMoveUi',
  DUMMY = 'DummyUi',
  BATTLE = 'BattleUi',
}
