export const enum SFX {
  CURSOR_0 = 'cursor_0',
  OPEN_0 = 'open_0',
  BUZZER = 'buzzer',
  DOOR_0 = 'door_0',
  DOOR_1 = 'door_1',
  DOOR_2 = 'door_2',
  CONGRATULATIONS = 'cong',
  GET_0 = 'get_0',
  EMO = 'emo',
  THROW = 'throw',
  BALL_ENTER = 'ball_enter',
  BALL_EXIT = 'ball_exit',
  BALL_DROP = 'ball_drop',
  BALL_SHAKE = 'ball_shake',
  BALL_CATCH = 'ball_catch',
  FLEE = 'flee',
  REWARD = 'reward',
  EVOL_0 = 'evol_0',
  EVOL_1 = 'evol_1',
  HATCH = 'hatch',
  PC_ACCESS = 'pc_access',
  PC_CLOSE = 'pc_close',
  PC_PICK_UP = 'pc_pick_up',
  PC_PUT_DOWN = 'pc_put_down',
  BAG_CURSOR = 'bag_cursor',
  BICYCLE = 'bicycle',
  EXP_GAIN = 'exp_gain',
  EXP_FULL = 'exp_full',
  MART = 'mart',
}

export const enum BGM {}
