export const enum TEXTURE {
  LOGO_0 = 'logo_0',
  LOGO_1 = 'logo_1',
  LOGO_DISCORD = 'logo_discord',
  LOGO_GITHUB = 'logo_github',

  BLANK = 'blank',
  TYPES = 'types',
  TYPES_EMPTY = 'types_empty',

  BG_0 = 'bg_0',
  BG_1 = 'bg_1',
  BG_2 = 'bg_2',
  BG_3 = 'bg_3',
  BG_4 = 'bg_4',
  BG_5 = 'bg_5',
  BG_6 = 'bg_6',
  BG_7 = 'bg_7',
  BG_8 = 'bg_8',
  BG_9 = 'bg_9',
  BG_10 = 'bg_10',
  BG_11 = 'bg_11',
  BG_12 = 'bg_12',
  BG_BLACK = 'bg_black',
  BG_PC = 'bg_pc',
  BG_EVOLVE = 'bg_evolve',
  BG_BAG_M = 'bg_bag_m',
  BG_BAG_F = 'bg_bag_f',
  BG_MART = 'bg_mart',
  BG_MART_SELL = 'bg_mart_sell',
  BG_POKE_RADER = 'bg_poke-rader',
  BG_MAP = 'bg_map',
  MAP_ISLAND = 'map_island',
  MAP_TITLE = 'map_title',
  MAP_CURSOR = 'map_cursor',
  MAP_POINT_0 = 'map_point_0',
  MAP_POINT_0_SEL = 'map_point_0_sel',
  MAP_POINT_1 = 'map_point_1',
  MAP_POINT_1_SEL = 'map_point_1_sel',
  MAP_PLAYER = 'map_player',
  MAP_CURSOR_SEL = 'map_cursor_sel',

  BG_POKEDEX = 'bg_pokedex',
  POKEDEX_TITLE = 'pokedex-title',
  OWNED = 'owned',

  WINDOW_0 = 'window_0',
  WINDOW_1 = 'window_1',
  WINDOW_2 = 'window_2',
  WINDOW_3 = 'window_3',
  WINDOW_GUIDE = 'window_guide',
  WINDOW_WHITE = 'window_white',
  WINDOW_CURSOR = 'window_cursor',
  WINDOW_CURSOR_R = 'window_cursor_r',
  WINDOW_HUD = 'window_hud',
  WINDOW_NOTICE_0 = 'window_notice_0',
  WINDOW_NOTICE_1 = 'window_notice_1',
  WINDOW_NOTICE_2 = 'window_notice_2',
  WINDOW_PC = 'window_pc',
  WINDOW_EXP = 'window_exp',
  WINDOW_MAP = 'window_map',
  WINDOW_COMMON = 'window_common',
  WINDOW_RARE = 'window_rare',
  WINDOW_EPIC = 'window_epic',
  WINDOW_LEGENDARY = 'window_legendary',
  KEYCAP = 'keycap',

  CURSOR_WHITE = 'cursor_w',
  CURSOR_BLACK = 'cursor_b',
  CURSOR_FINGER = 'cursor_finger',
  CURSOR_MOUSE = 'cursor_mouse',

  SLIDER = 'slider',
  SLIDER_BG = 'slider_b',

  ICON_CHECK = 'icon_check',
  ICON_RUNNING = 'icon_running',
  ICON_MENU = 'icon_menu',
  ICON_TALK = 'icon_talk',
  ICON_LOCATION = 'icon_location',
  ICON_MONEY = 'icon_money',
  ICON_XY = 'icon_xy',
  ICON_CANDY = 'icon_candy',
  ICON_DAWN = 'icon_dawn',
  ICON_DAY = 'icon_day',
  ICON_DUSK = 'icon_dusk',
  ICON_NIGHT = 'icon_night',
  ICON_DAWN_1 = 'icon_dawn_1',
  ICON_DAY_1 = 'icon_day_1',
  ICON_DUSK_1 = 'icon_dusk_1',
  ICON_NIGHT_1 = 'icon_night_1',
  ICON_POKEDEX = 'icon_pokedex',
  ICON_PC = 'icon_pc',
  ICON_BAG_M = 'icon_bag_male',
  ICON_BAG_F = 'icon_bag_female',
  ICON_OPTION = 'icon_option',
  ICON_EXIT_0 = 'icon_exit_0',
  ICON_EXIT_1 = 'icon_exit_1',
  ICON_CANCEL = 'icon_cancel',
  ICON_SHINY = 'icon_shiny',
  ICON_OWNED = 'icon_owned',
  ICON_RATE_UP = 'up_rate',
  ICON_RATE_DOWN = 'down_rate',
  ICON_LV = 'icon_lv',
  ICON_REGISTER = 'icon_register',
  ICON_DISCORD = 'icon_discord',
  ICON_GOOGLE = 'icon_google',
  ICON_POKE_RADER = 'icon_poke-rader',
  ICON_MAP = 'icon_map',

  ICON_SUNNY = 'icon_sunny',
  ICON_RAINY = 'icon_rainy',
  ICON_STORMY = 'icon_stormy',
  ICON_FOGGY = 'icon_foggy',
  ICON_SANDWIND = 'icon_sandwind',
  ICON_SANDSTORM = 'icon_sandstorm',
  ICON_SNOWY = 'icon_snowy',
  ICON_BLIZZARD = 'icon_blizzard',

  GROUND_ITEM = 'ground_item',
  EMO = 'emo',
  SPARKLE = 'sparkle',
  OVERWORLD_SHINY = 'overworld_shiny',
  OVERWORLD_GRASS_1 = 'overworld_grass_1',
  OVERWORLD_GRASS_1_B = 'overworld_grass_1_b',
  OVERWORLD_GRASS_2 = 'overworld_grass_2',
  OVERWORLD_GRASS_2_B = 'overworld_grass_2_b',
  SAFARI_BALL_THROW = 'safari-ball_0',
  SAFARI_BALL_OPEN = 'safari-ball_1',
  SAFARI_STAR = 'safari_star',
  REG = 'reg',

  OVERWORLD_SHADOW = 'overworld_shadow',
  LIGHT = 'light',

  //pc
  PC_INFO = 'pc_info',
  PARTICLE_EVOL = 'particle_evol',
  PC_BGS = 'pc_pgs',
  PC_FINGER_0 = 'pc_finger_0',
  PC_FINGER_1 = 'pc_finger_1',
  PC_SAFARI_BALL = 'pc_safari-ball',
  PC_ULTRA_BALL = 'pc_ultra-ball',
  PC_MASTER_BALL = 'pc_master-ball',

  PET_EMO = 'pet_emo',

  BG_HM = 'bg_hm',
  PARTICLE_HM_0 = 'particle_hm_0',
  PARTICLE_HM_1 = 'particle_hm_1',

  BALL_BURST_DAZZLE = 'ball_burst_dazzle',
  BALL_BURST_PARTICLE_S = 'ball_burst_particle_s',
  BALL_BURST_PARTICLE = 'ball_burst_particle',
  BALL_BURST_RING = 'ball_burst_ring',
  BALL_BURST_RAY = 'ball_burst_ray',

  BASE_SURF = 'base_surf',
  OVERWORLD_FOOTPRINT_0 = 'overworld_footprint_0',
  OVERWORLD_FOOTPRINT_1 = 'overworld_footprint_1',
  OVERWORLD_FOOTPRINT_2 = 'overworld_footprint_2',
}

export const enum ANIMATION {
  PLAYER_OVERWORLD_SKIN = 'player_overworld_skin',
  PLAYER_OVERWORLD_WALK_DOWN = 'player_overworld_walk_down',
  PLAYER_OVERWORLD_WALK_LEFT = 'player_overworld_walk_left',
  PLAYER_OVERWORLD_WALK_RIGHT = 'player_overworld_walk_right',
  PLAYER_OVERWORLD_WALK_UP = 'player_overworld_walk_up',
  PLAYER_OVERWORLD_RUNNING_DOWN = 'player_overworld_running_down',
  PLAYER_OVERWORLD_RUNNING_LEFT = 'player_overworld_running_left',
  PLAYER_OVERWORLD_RUNNING_RIGHT = 'player_overworld_running_right',
  PLAYER_OVERWORLD_RUNNING_UP = 'player_overworld_running_up',
  PLAYER_OVERWORLD_RIDE_DOWN = 'player_overworld_ride_down',
  PLAYER_OVERWORLD_RIDE_LEFT = 'player_overworld_ride_left',
  PLAYER_OVERWORLD_RIDE_RIGHT = 'player_overworld_ride_right',
  PLAYER_OVERWORLD_RIDE_UP = 'player_overworld_ride_up',
  PLAYER_OVERWORLD_SURF_DOWN = 'player_overworld_surf_down',
  PLAYER_OVERWORLD_SURF_LEFT = 'player_overworld_surf_left',
  PLAYER_OVERWORLD_SURF_RIGHT = 'player_overworld_surf_right',
  PLAYER_OVERWORLD_SURF_UP = 'player_overworld_surf_up',
  PLAYER_OVERWORLD_FISHING_DOWN = 'player_overworld_fishing_down',
  PLAYER_OVERWORLD_FISHING_LEFT = 'player_overworld_fishing_left',
  PLAYER_OVERWORLD_FISHING_RIGHT = 'player_overworld_fishing_right',
  PLAYER_OVERWORLD_FISHING_UP = 'player_overworld_fishing_up',
  PLAYER_BACK_SKIN = 'player_back_skin',
  NPC = 'npc',
  DOOR = 'door',
  OVERWORLD_SHINY = 'overworld_shiny',
  OVERWORLD_GRASS_1 = 'overworld_grass_1',
  OVERWORLD_GRASS_1_B = 'overworld_grass_1_b',
  OVERWORLD_GRASS_2 = 'overworld_grass_2',
  OVERWORLD_GRASS_2_B = 'overworld_grass_2_b',
  MAP_CURSOR_SEL = 'map_cursor_sel_anim',
  MAP_PLAYER = 'map_player_anim',
  BASE_SURF_DOWN = 'base_surf_down',
  BASE_SURF_LEFT = 'base_surf_left',
  BASE_SURF_RIGHT = 'base_surf_right',
  BASE_SURF_UP = 'base_surf_up',
}

export const enum TILE {
  //indoor
  INDOOR_FLOOR = 'indoor_floor',
  INDOOR_OBJECT = 'indoor_object',
  INDOOR_EVENT = 'indoor_event',

  //outdoor
  OUTDOOR_FLOOR = 'outdoor_floor',
  OUTDOOR_EDGE = 'outdoor_edge',
  OUTDOOR_OBJECT = 'outdoor_object',
  OUTDOOR_OBJECT_URBAN = 'outdoor_object_urban',
  OUTDOOR_URBAN = 'outdoor_urban',
  OUTDOOR_EVENT = 'outdoor_event',
}

export const enum MAP {
  //plaza
  PLAZA_001 = 'p001',
  PLAZA_002 = 'p002',
  PLAZA_003 = 'p003',
  PLAZA_004 = 'p004',
  PLAZA_005 = 'p005',
  PLAZA_006 = 'p006',
  PLAZA_007 = 'p007',
  PLAZA_008 = 'p008',
  PLAZA_009 = 'p009',

  //gate

  //safari
  SAFARI_000 = 's000',
  SAFARI_001 = 's001',
  SAFARI_002 = 's002',
  SAFARI_003 = 's003',
  SAFARI_004 = 's004',
  SAFARI_005 = 's005',
  SAFARI_006 = 's006',
  SAFARI_007 = 's007',
  SAFARI_008 = 's008',
  SAFARI_009 = 's009',
  SAFARI_010 = 's010',
  SAFARI_011 = 's011',
  SAFARI_012 = 's012',
  SAFARI_013 = 's013',
  SAFARI_014 = 's014',
  SAFARI_015 = 's015',
  SAFARI_016 = 's016',
  SAFARI_017 = 's017',
  SAFARI_018 = 's018',
  SAFARI_019 = 's019',
  SAFARI_020 = 's020',
  SAFARI_021 = 's021',
  SAFARI_022 = 's022',
  SAFARI_023 = 's023',
  SAFARI_024 = 's024',
  SAFARI_025 = 's025',
  SAFARI_026 = 's026',
  SAFARI_027 = 's027',
  SAFARI_028 = 's028',
  SAFARI_029 = 's029',
  SAFARI_030 = 's030',
  SAFARI_031 = 's031',
  SAFARI_032 = 's032',
  SAFARI_033 = 's033',
  SAFARI_034 = 's034',
  SAFARI_035 = 's035',
  SAFARI_036 = 's036',
  SAFARI_037 = 's037',
  SAFARI_038 = 's038',
  SAFARI_039 = 's039',
  SAFARI_040 = 's040',
  SAFARI_041 = 's041',
  SAFARI_042 = 's042',
  SAFARI_043 = 's043',
  SAFARI_044 = 's044',
  SAFARI_045 = 's045',
  SAFARI_046 = 's046',
}
