import { MapConfig } from '@poposafari/core/map.registry';
import { BGM, DEPTH, TEXTURE, TILE } from '@poposafari/types';
import { DIRECTION } from '../overworld.constants';
import { DOOR, INIT_POS } from './door';

export const p001Config: MapConfig = {
  key: 'p001',
  bgm: BGM.P001_1,
  isIndoor: false,
  area: { land: 'p001', water: 'p001' },
  type: 'plaza',
  dayNightFilter: true,
  allowRide: true,
  tilesets: [
    TILE.OUTDOOR_FLOOR,
    TILE.OUTDOOR_OBJECT,
    TILE.OUTDOOR_EDGE,
    TILE.OUTDOOR_OBJECT_URBAN,
    TILE.OUTDOOR_URBAN,
    TILE.OUTDOOR_EVENT,
  ],
  layers: [
    { idx: 0, texture: TILE.OUTDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.OUTDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.OUTDOOR_EDGE, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.OUTDOOR_EDGE, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.OUTDOOR_URBAN, depth: DEPTH.GROUND + 4 },
    { idx: 5, texture: TILE.OUTDOOR_URBAN, depth: DEPTH.GROUND + 5 },
    { idx: 6, texture: TILE.OUTDOOR_OBJECT, depth: DEPTH.GROUND + 6 },
    { idx: 7, texture: TILE.OUTDOOR_OBJECT, depth: DEPTH.GROUND + 7 },
    { idx: 8, texture: TILE.OUTDOOR_OBJECT_URBAN, depth: DEPTH.GROUND + 8 },
    { idx: 9, texture: TILE.OUTDOOR_OBJECT_URBAN, depth: DEPTH.GROUND + 9 },
    { idx: 10, texture: TILE.OUTDOOR_EVENT, depth: DEPTH.GROUND + 10 },
  ],
  foreground: [
    {
      idx: 11,
      texture: [
        TILE.OUTDOOR_OBJECT_URBAN,
        TILE.OUTDOOR_OBJECT,
        TILE.OUTDOOR_URBAN,
        TILE.OUTDOOR_EDGE,
      ],
      depth: DEPTH.FOREGROUND,
    },
    {
      idx: 12,
      texture: [
        TILE.OUTDOOR_OBJECT_URBAN,
        TILE.OUTDOOR_OBJECT,
        TILE.OUTDOOR_URBAN,
        TILE.OUTDOOR_EDGE,
      ],
      depth: DEPTH.FOREGROUND,
    },
  ],

  doors: [
    { startId: DOOR.P001_BOUTIQUE, destId: INIT_POS.P002_DOWN_0 },
    { startId: DOOR.P001_MART, destId: INIT_POS.P003_DOWN_0 },
    { startId: DOOR.P001_BIKE, destId: INIT_POS.P004_DOWN_0 },
    { startId: DOOR.P001_NPC1, destId: INIT_POS.P005_DOWN_0 },
    { startId: DOOR.P001_NPC2, destId: INIT_POS.P006_DOWN_0 },
    { startId: DOOR.P001_LAB, destId: INIT_POS.P008_DOWN_0 },
    { startId: DOOR.P001_NPC3, destId: INIT_POS.P009_DOWN_0 },
  ],

  npcs: [
    {
      key: 'npc25',
      name: 'cabbie_safari',
      special: 'safari',
      x: 43,
      y: 21,
      direction: DIRECTION.DOWN,
      reaction: [],
    },
    {
      key: 'npc_1_0',
      name: 'musician',
      special: 'musician',
      x: 57,
      y: 28,
      direction: DIRECTION.DOWN,
      reaction: [],
    },
    {
      key: '',
      name: '',
      x: 58,
      y: 28,
      direction: DIRECTION.DOWN,
      type: 'pokemon',
      pokedexId: '0402',
      isShiny: false,
      path: [],
      reaction: [{ key: 'talk', content: { text: ['msg:npc1_0', 'msg:npc1_1'], name: 'NPC' } }],
    },
    {
      key: '',
      name: '',
      x: 42,
      y: 21,
      direction: DIRECTION.DOWN,
      type: 'pokemon',
      pokedexId: '0823',
      isShiny: false,
      path: [],
      reaction: [{ key: 'talk', content: { text: ['msg:npc1_0', 'msg:npc1_1'], name: 'NPC' } }],
    },

    {
      key: TEXTURE.BLANK,
      name: '',
      x: 31,
      y: 28,
      direction: DIRECTION.RIGHT,
      reaction: [
        {
          key: 'notice',
          content: { text: ['object:sign_boutique'], name: '', window: TEXTURE.WINDOW_NOTICE_0 },
        },
      ],
    },
    {
      key: TEXTURE.BLANK,
      name: '',
      x: 46,
      y: 28,
      direction: DIRECTION.RIGHT,
      reaction: [
        {
          key: 'notice',
          content: { text: ['object:sign_bike_shop'], name: '', window: TEXTURE.WINDOW_NOTICE_0 },
        },
      ],
    },
    {
      key: TEXTURE.BLANK,
      name: '',
      x: 38,
      y: 28,
      direction: DIRECTION.RIGHT,
      reaction: [
        {
          key: 'notice',
          content: { text: ['object:sign_mart'], name: '', window: TEXTURE.WINDOW_NOTICE_0 },
        },
      ],
    },
    {
      key: TEXTURE.BLANK,
      name: '',
      x: 34,
      y: 44,
      direction: DIRECTION.RIGHT,
      reaction: [
        {
          key: 'notice',
          content: { text: ['object:sign_lab'], name: '', window: TEXTURE.WINDOW_NOTICE_0 },
        },
      ],
    },
    // ── [TEST] 이동 NPC: 사람 ─────────────────────────────────────
    {
      key: 'npc18',
      name: '',
      x: 51,
      y: 32,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [
        { direction: DIRECTION.DOWN, tiles: 2, delayMs: 1200 },
        { direction: DIRECTION.UP, tiles: 2, delayMs: 1200 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_1'], name: 'NPC' } }],
    },
    {
      key: 'npc27',
      name: '',
      x: 39,
      y: 29,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [
        { direction: DIRECTION.RIGHT, tiles: 2, delayMs: 2000 },
        { direction: DIRECTION.LEFT, tiles: 2, delayMs: 2000 },
      ],
      reaction: [
        {
          key: 'talk',
          content: { text: ['object:npc_script_0'], name: 'NPC' },
        },
      ],
    },
    {
      key: 'npc19',
      name: '',
      x: 52,
      y: 40,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [
        {
          key: 'talk',
          content: { text: ['object:npc_script_8', 'object:npc_script_17'], name: 'NPC' },
        },
      ],
    },
    {
      key: '',
      name: '',
      x: 53,
      y: 40,
      direction: DIRECTION.DOWN,
      type: 'pokemon',
      pokedexId: '0835',
      isShiny: false,
      path: [],
      reaction: [{ key: 'talk', content: { text: ['msg:npc1_0', 'msg:npc1_1'], name: 'NPC' } }],
    },
    {
      key: 'npc30',
      name: '',
      x: 33,
      y: 22,
      direction: DIRECTION.UP,
      type: 'human',
      path: [{ direction: DIRECTION.UP, tiles: 0, delayMs: 2000 }],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_6'], name: 'NPC' } }],
    },
    {
      key: 'npc12',
      name: '',
      x: 55,
      y: 13,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_7'], name: 'NPC' } }],
    },
    {
      key: '',
      name: '',
      x: 56,
      y: 13,
      direction: DIRECTION.DOWN,
      type: 'pokemon',
      pokedexId: '0446',
      isShiny: false,
      path: [],
      reaction: [{ key: 'talk', content: { text: ['msg:npc1_0', 'msg:npc1_1'], name: 'NPC' } }],
    },
  ],
};

export const p002Config: MapConfig = {
  key: 'p002',
  bgm: BGM.P001_1,
  isIndoor: true,
  area: { land: 'p002', water: 'p002' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P002_DOWN_0, destId: INIT_POS.P001_BOUTIQUE },
    { startId: DOOR.P002_DOWN_1, destId: INIT_POS.P001_BOUTIQUE },
  ],
  npcs: [
    {
      key: 'npc34',
      name: 'shopkeeper',
      x: 6,
      y: 5,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [],
    },
    {
      key: TEXTURE.BLANK,
      name: '',
      x: 6,
      y: 6,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [{ key: 'talk', content: { text: ['object:coming_soon'], name: 'NPC' } }],
    },
    {
      key: 'npc34',
      name: 'shopkeeper',
      x: 7,
      y: 5,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [],
    },
    {
      key: TEXTURE.BLANK,
      name: '',
      x: 7,
      y: 6,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [{ key: 'talk', content: { text: ['object:coming_soon'], name: 'NPC' } }],
    },
  ],
};

export const p003Config: MapConfig = {
  key: 'p003',
  bgm: BGM.POKEMART,
  isIndoor: true,
  area: { land: 'p003', water: 'p003' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P003_DOWN_0, destId: INIT_POS.P001_MART },
    { startId: DOOR.P003_DOWN_1, destId: INIT_POS.P001_MART },
  ],
  npcs: [
    {
      key: TEXTURE.BLANK,
      name: '',
      special: 'mart',
      martItems: [
        'fire-stone',
        'water-stone',
        'thunder-stone',
        'leaf-stone',
        'moon-stone',
        'sun-stone',
        'shiny-stone',
        'dusk-stone',
        'dawn-stone',
        'ice-stone',
        'oval-stone',
        'metal-coat',
        'up-grade',
        'kings-rock',
        'dragon-scale',
        'deep-sea-scale',
        'deep-sea-tooth',
        'dubious-disc',
        'magmarizer',
        'electirizer',
        'reaper-cloth',
        'protector',
        'razor-claw',
        'razor-fang',
        'prism-scale',
        'whipped-dream',
        'sachet',
        'cracked-pot',
        'chipped-pot',
        'tart-apple',
        'sweet-apple',
        'flower-sweet',
        'clover-sweet',
        'strawberry-sweet',
        'ribbon-sweet',
        'berry-sweet',
        'star-sweet',
        'love-sweet',
        'galarica-cuff',
        'galarica-wreath',
        'linking-cord',
        'black-augurite',
        'peat-block',
        'syrupy-apple',
        'scroll-of-darkness',
        'scroll-of-waters',
        'malicious-armor',
        'auspicious-armor',
        'unremarkable-teacup',
        'masterpiece-teacup',
        'leek',
        'metal-alloy',
      ],
      x: 3,
      y: 4,
      direction: DIRECTION.DOWN,
      reaction: [],
    },

    {
      key: TEXTURE.BLANK,
      name: '',
      special: 'mart',
      martItems: [
        'safari-ball',
        'safari-zone-ticket',
        'move_surf',
        'move_ancient-power',
        'move_double-hit',
        'move_dragon-pulse',
        'move_hyper-drill',
        'move_mimic',
        'move_rollout',
        'move_stomp',
        'move_taunt',
        'move_twin-beam',
        'move_rage-fist',
        'move_barb-barrage',
        'move_psyshield-bash',
        'move_double-edge',
        'move_dragon-cheer',
      ],
      x: 3,
      y: 5,
      direction: DIRECTION.DOWN,
      reaction: [],
    },
    {
      key: 'npc7',
      name: 'shopkeeper_0',
      x: 2,
      y: 4,
      direction: DIRECTION.RIGHT,
      type: 'human',
      path: [],
      reaction: [],
    },
    {
      key: 'npc7',
      name: 'shopkeeper_1',
      x: 2,
      y: 5,
      direction: DIRECTION.RIGHT,
      type: 'human',
      path: [],
      reaction: [],
    },
    {
      key: 'npc6',
      name: '',
      x: 9,
      y: 3,
      direction: DIRECTION.UP,
      type: 'human',
      path: [],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_3'], name: 'NPC' } }],
    },
    {
      key: 'npc33',
      name: '',
      x: 8,
      y: 6,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [
        { direction: DIRECTION.UP, tiles: 1, delayMs: 2000 },
        { direction: DIRECTION.DOWN, tiles: 2, delayMs: 2000 },
        { direction: DIRECTION.UP, tiles: 1, delayMs: 1500 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_2'], name: 'NPC' } }],
    },
  ],
};

export const p004Config: MapConfig = {
  key: 'p004',
  bgm: BGM.P001_1,
  isIndoor: true,
  area: { land: 'p004', water: 'p004' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P004_DOWN_0, destId: INIT_POS.P001_BIKE },
    { startId: DOOR.P004_DOWN_1, destId: INIT_POS.P001_BIKE },
  ],
  npcs: [
    {
      key: 'npc3',
      name: '',
      special: 'mart',
      martItems: ['bicycle'],
      x: 8,
      y: 6,
      direction: DIRECTION.DOWN,
      reaction: [],
    },
  ],
};

export const p005Config: MapConfig = {
  key: 'p005',
  bgm: BGM.P001_1,
  showLocationBanner: false,
  isIndoor: true,
  area: { land: 'p005', water: 'p005' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P005_DOWN_0, destId: INIT_POS.P001_NPC1 },
    { startId: DOOR.P005_DOWN_1, destId: INIT_POS.P001_NPC1 },
  ],
  npcs: [
    {
      key: 'npc24',
      name: '',
      x: 12,
      y: 4,
      direction: DIRECTION.UP,
      type: 'human',
      path: [],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_5'], name: 'NPC' } }],
    },
    {
      key: 'npc19',
      name: '',
      x: 8,
      y: 6,
      direction: DIRECTION.UP,
      type: 'human',
      path: [
        { direction: DIRECTION.LEFT, tiles: 2, delayMs: 2000 },
        { direction: DIRECTION.DOWN, tiles: 0, delayMs: 500 },
        { direction: DIRECTION.RIGHT, tiles: 2, delayMs: 2000 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_4'], name: 'NPC' } }],
    },
  ],
};

export const p006Config: MapConfig = {
  key: 'p006',
  bgm: BGM.P001_1,
  showLocationBanner: false,
  isIndoor: true,
  area: { land: 'p006', water: 'p006' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P006_DOWN_0, destId: INIT_POS.P001_NPC2 },
    { startId: DOOR.P006_DOWN_1, destId: INIT_POS.P001_NPC2 },
    { startId: DOOR.P006_RIGHT_0, destId: INIT_POS.P007_LEFT_0 },
  ],
  npcs: [
    {
      key: 'npc29',
      name: '',
      x: 3,
      y: 4,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [
        {
          key: 'talk',
          content: { text: ['object:npc_script_10', 'object:npc_script_11'], name: 'NPC' },
        },
      ],
    },
    {
      key: 'npc31',
      name: '',
      x: 4,
      y: 12,
      direction: DIRECTION.LEFT,
      type: 'human',
      path: [
        { direction: DIRECTION.LEFT, tiles: 2, delayMs: 2000 },
        { direction: DIRECTION.DOWN, tiles: 0, delayMs: 1000 },
        { direction: DIRECTION.UP, tiles: 0, delayMs: 1000 },
        { direction: DIRECTION.RIGHT, tiles: 2, delayMs: 2000 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_9'], name: 'NPC' } }],
    },
  ],
};

export const p007Config: MapConfig = {
  key: 'p007',
  bgm: BGM.P001_1,
  showLocationBanner: false,
  isIndoor: true,
  area: { land: 'p007', water: 'p007' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P007_LEFT_0, destId: INIT_POS.P006_RIGHT_0 },
    { startId: DOOR.P007_LEFT_1, destId: INIT_POS.P006_RIGHT_0 },
  ],
  npcs: [
    {
      key: 'npc10',
      name: '',
      x: 3,
      y: 13,
      direction: DIRECTION.LEFT,
      type: 'human',
      path: [
        { direction: DIRECTION.RIGHT, tiles: 2, delayMs: 2000 },
        { direction: DIRECTION.DOWN, tiles: 0, delayMs: 1000 },
        { direction: DIRECTION.UP, tiles: 0, delayMs: 1000 },
        { direction: DIRECTION.LEFT, tiles: 2, delayMs: 2000 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_12'], name: 'NPC' } }],
    },
  ],
};

export const p008Config: MapConfig = {
  key: 'p008',
  bgm: BGM.P001_1,
  isIndoor: true,
  area: { land: 'p008', water: 'p008' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P008_DOWN_0, destId: INIT_POS.P001_LAB },
    { startId: DOOR.P008_DOWN_1, destId: INIT_POS.P001_LAB },
  ],
  npcs: [
    {
      key: 'npc0',
      name: 'professor',
      x: 11,
      y: 5,
      direction: DIRECTION.DOWN,
      type: 'human',
      path: [],
      reaction: [
        {
          key: 'talk',
          content: { text: ['object:npc_script_15', 'object:npc_script_18'], name: 'NPC' },
        },
      ],
    },
    {
      key: 'npc8',
      name: '',
      x: 6,
      y: 11,
      direction: DIRECTION.UP,
      type: 'human',
      path: [
        { direction: DIRECTION.LEFT, tiles: 1, delayMs: 1000 },
        { direction: DIRECTION.UP, tiles: 0, delayMs: 400 },
        { direction: DIRECTION.LEFT, tiles: 2, delayMs: 1000 },
        { direction: DIRECTION.UP, tiles: 0, delayMs: 400 },
        { direction: DIRECTION.RIGHT, tiles: 3, delayMs: 1000 },
      ],
      reaction: [{ key: 'talk', content: { text: ['object:npc_script_13'], name: 'NPC' } }],
    },
    {
      key: 'npc1',
      name: '',
      x: 14,
      y: 11,
      direction: DIRECTION.UP,
      type: 'human',
      path: [],
      reaction: [
        {
          key: 'talk',
          content: { text: ['object:npc_script_14', 'object:npc_script_19'], name: 'NPC' },
        },
      ],
    },
    {
      key: 'npc33',
      name: 'fossil_restorer',
      special: 'fossil',
      x: 7,
      y: 13,
      direction: DIRECTION.DOWN,
      reaction: [],
    },
  ],
};

export const p009Config: MapConfig = {
  key: 'p009',
  bgm: BGM.P009,
  showLocationBanner: false,
  isIndoor: true,
  area: { land: 'p009', water: 'p009' },
  type: 'plaza',
  dayNightFilter: false,
  weatherFilter: false,
  allowRide: false,
  tilesets: [TILE.INDOOR_FLOOR, TILE.INDOOR_OBJECT, TILE.INDOOR_EVENT],
  layers: [
    { idx: 0, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND },
    { idx: 1, texture: TILE.INDOOR_FLOOR, depth: DEPTH.GROUND + 1 },
    { idx: 2, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 2 },
    { idx: 3, texture: TILE.INDOOR_OBJECT, depth: DEPTH.GROUND + 3 },
    { idx: 4, texture: TILE.INDOOR_EVENT, depth: DEPTH.GROUND + 4 },
  ],
  foreground: [
    { idx: 5, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
    { idx: 6, texture: [TILE.INDOOR_OBJECT], depth: DEPTH.FOREGROUND },
  ],

  doors: [
    { startId: DOOR.P009_DOWN_0, destId: INIT_POS.P001_NPC3 },
    { startId: DOOR.P009_DOWN_1, destId: INIT_POS.P001_NPC3 },
  ],
  npcs: [],
};
