import { BATTLE_AREA, ItemCategory, ItemData, NpcData } from './enums';

const initialItemData: Record<string, ItemData> = {
  'master-ball': {
    id: 'master-ball',
    comment: '마스터볼',
    type: ItemCategory.POKEBALL,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: false,
    sellable: false,
    usable: false,
    registerable: false,
  },
  'poke-ball': {
    id: 'poke-ball',
    comment: '몬스터볼',
    type: ItemCategory.POKEBALL,
    buyPrice: 200,
    sellPrice: 100,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'great-ball': {
    id: 'great-ball',
    comment: '수퍼볼',
    type: ItemCategory.POKEBALL,
    buyPrice: 600,
    sellPrice: 300,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'ultra-ball': {
    id: 'ultra-ball',
    comment: '하이퍼볼',
    type: ItemCategory.POKEBALL,
    buyPrice: 1200,
    sellPrice: 600,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'occa-berry': {
    id: 'occa-berry',
    comment: '오카열매(불)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'passho-berry': {
    id: 'passho-berry',
    comment: '꼬시개열매(물)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'wacan-berry': {
    id: 'wacan-berry',
    comment: '초나열매(전기)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'rindo-berry': {
    id: 'rindo-berry',
    comment: '린드열매(풀)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'yache-berry': {
    id: 'yache-berry',
    comment: '플카열매(얼음)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'chople-berry': {
    id: 'chople-berry',
    comment: '로플열매(격투)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'kebia-berry': {
    id: 'kebia-berry',
    comment: '으름열매(독)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'shuca-berry': {
    id: 'shuca-berry',
    comment: '슈캐열매(땅)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'coba-berry': {
    id: 'coba-berry',
    comment: '바코열매(비행)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'payapa-berry': {
    id: 'payapa-berry',
    comment: '야파열매(에스퍼)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'tanga-berry': {
    id: 'tanga-berry',
    comment: '리체열매(벌레)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'charti-berry': {
    id: 'charti-berry',
    comment: '루미열매(바위)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'kasib-berry': {
    id: 'kasib-berry',
    comment: '수불열매(고스트)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'haban-berry': {
    id: 'haban-berry',
    comment: '하반열매(드래곤)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'colbur-berry': {
    id: 'colbur-berry',
    comment: '마코열매(악)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'babiri-berry': {
    id: 'babiri-berry',
    comment: '바리비열매(강철)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'roseli-berry': {
    id: 'roseli-berry',
    comment: '로셀열매(페어리)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'chilan-berry': {
    id: 'chilan-berry',
    comment: '카리열매(노말)',
    type: ItemCategory.BERRY,
    buyPrice: 1000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'enigma-berry': {
    id: 'enigma-berry',
    comment: '의문열매(all)',
    type: ItemCategory.BERRY,
    buyPrice: 2000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  mud: {
    id: 'mud',
    comment: '진흙',
    type: ItemCategory.ETC,
    buyPrice: 1000,
    sellPrice: 100,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'fire-stone': {
    id: 'fire-stone',
    comment: '불꽃의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'water-stone': {
    id: 'water-stone',
    comment: '물의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'thunder-stone': {
    id: 'thunder-stone',
    comment: '천둥의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'leaf-stone': {
    id: 'leaf-stone',
    comment: '리프의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'moon-stone': {
    id: 'moon-stone',
    comment: '달의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'sun-stone': {
    id: 'sun-stone',
    comment: '태양의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'shiny-stone': {
    id: 'shiny-stone',
    comment: '빛의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'dusk-stone': {
    id: 'dusk-stone',
    comment: '어둠의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'dawn-stone': {
    id: 'dawn-stone',
    comment: '각성의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'oval-stone': {
    id: 'oval-stone',
    comment: '동글동글돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'ice-stone': {
    id: 'ice-stone',
    comment: '얼음의돌',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'metal-coat': {
    id: 'metal-coat',
    comment: '금속코트',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'up-grade': {
    id: 'up-grade',
    comment: '업그레이드',
    type: ItemCategory.ETC,
    buyPrice: 40000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'kings-rock': {
    id: 'kings-rock',
    comment: '왕의징표석',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 600,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'dragon-scale': {
    id: 'dragon-scale',
    comment: '용의비늘',
    type: ItemCategory.ETC,
    buyPrice: 5000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'deep-sea-scale': {
    id: 'deep-sea-scale',
    comment: '심해의비늘',
    type: ItemCategory.ETC,
    buyPrice: 5000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'deep-sea-tooth': {
    id: 'deep-sea-tooth',
    comment: '심해의이빨',
    type: ItemCategory.ETC,
    buyPrice: 6000,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'dubious-disc': {
    id: 'dubious-disc',
    comment: '괴상한패치',
    type: ItemCategory.ETC,
    buyPrice: 40000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  magmarizer: {
    id: 'magmarizer',
    comment: '마그마부스터',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  electirizer: {
    id: 'electirizer',
    comment: '에레키부스터',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'reaper-cloth': {
    id: 'reaper-cloth',
    comment: '영계의천',
    type: ItemCategory.ETC,
    buyPrice: 30000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  protector: {
    id: 'protector',
    comment: '프로텍터',
    type: ItemCategory.ETC,
    buyPrice: 30000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'razor-claw': {
    id: 'razor-claw',
    comment: '예리한손톱',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'razor-fang': {
    id: 'razor-fang',
    comment: '예리한이빨',
    type: ItemCategory.ETC,
    buyPrice: 20000,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'prism-scale': {
    id: 'prism-scale',
    comment: '고운비늘',
    type: ItemCategory.ETC,
    buyPrice: 15000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'whipped-dream': {
    id: 'whipped-dream',
    comment: '휘핑팝',
    type: ItemCategory.ETC,
    buyPrice: 15000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  sachet: {
    id: 'sachet',
    comment: '향기주머니',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'cracked-pot': {
    id: 'cracked-pot',
    comment: '깨진포트',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'chipped-pot': {
    id: 'chipped-pot',
    comment: '이빠진포트',
    type: ItemCategory.ETC,
    buyPrice: 19000,
    sellPrice: 2000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'tart-apple': {
    id: 'tart-apple',
    comment: '달콤한사과',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'sweet-apple': {
    id: 'sweet-apple',
    comment: '새콤한사과',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'flower-sweet': {
    id: 'flower-sweet',
    comment: '꽃사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'clover-sweet': {
    id: 'clover-sweet',
    comment: '네잎사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'strawberry-sweet': {
    id: 'strawberry-sweet',
    comment: '딸기사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'ribbon-sweet': {
    id: 'ribbon-sweet',
    comment: '리본사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'berry-sweet': {
    id: 'berry-sweet',
    comment: '베리사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'star-sweet': {
    id: 'star-sweet',
    comment: '스타사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'love-sweet': {
    id: 'love-sweet',
    comment: '하트사탕공예',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'galarica-cuff': {
    id: 'galarica-cuff',
    comment: '가라두구팔찌',
    type: ItemCategory.ETC,
    buyPrice: 18000,
    sellPrice: 2000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'galarica-wreath': {
    id: 'galarica-wreath',
    comment: '가라두구머리장식',
    type: ItemCategory.ETC,
    buyPrice: 18000,
    sellPrice: 2000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'linking-cord': {
    id: 'linking-cord',
    comment: '연결의끈',
    type: ItemCategory.ETC,
    buyPrice: 25000,
    sellPrice: 2050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'black-augurite': {
    id: 'black-augurite',
    comment: '검은휘석',
    type: ItemCategory.ETC,
    buyPrice: 21000,
    sellPrice: 2050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'peat-block': {
    id: 'peat-block',
    comment: '피트블록',
    type: ItemCategory.ETC,
    buyPrice: 18000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'scroll-of-darkness': {
    id: 'scroll-of-darkness',
    comment: '악의 족자',
    type: ItemCategory.ETC,
    buyPrice: 25000,
    sellPrice: 2050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'scroll-of-waters': {
    id: 'scroll-of-waters',
    comment: '물의 족자',
    type: ItemCategory.ETC,
    buyPrice: 25000,
    sellPrice: 2050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'malicious-armor': {
    id: 'malicious-armor',
    comment: '저주받은갑옷',
    type: ItemCategory.ETC,
    buyPrice: 18000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'auspicious-armor': {
    id: 'auspicious-armor',
    comment: '축복받은갑옷',
    type: ItemCategory.ETC,
    buyPrice: 18000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'syrupy-apple': {
    id: 'syrupy-apple',
    comment: '꿀맛사과',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 900,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'unremarkable-teacup': {
    id: 'unremarkable-teacup',
    comment: '범작찻잔',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 900,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'masterpiece-teacup': {
    id: 'masterpiece-teacup',
    comment: '걸작찻잔',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 900,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'metal-alloy': {
    id: 'metal-alloy',
    comment: '복합금속',
    type: ItemCategory.ETC,
    buyPrice: 15000,
    sellPrice: 1050,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  repel: {
    id: 'repel',
    comment: '벌레회피스프레이',
    type: ItemCategory.ETC,
    buyPrice: 350,
    sellPrice: 175,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: true,
  },
  'super-repel': {
    id: 'super-repel',
    comment: '실버스프레이',
    type: ItemCategory.ETC,
    buyPrice: 500,
    sellPrice: 250,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: true,
  },
  'max-repel': {
    id: 'max-repel',
    comment: '골드스프레이',
    type: ItemCategory.ETC,
    buyPrice: 800,
    sellPrice: 400,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: true,
  },
  nugget: {
    id: 'nugget',
    comment: '금구슬',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 5000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'slowpoke-tail': {
    id: 'slowpoke-tail',
    comment: '맛있는꼬리',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 4900,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  stardust: {
    id: 'stardust',
    comment: '별의모래',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'star-piece': {
    id: 'star-piece',
    comment: '별의조각',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 4900,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'tiny-mushroom': {
    id: 'tiny-mushroom',
    comment: '작은버섯',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 300,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  pearl: {
    id: 'pearl',
    comment: '진주',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 700,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'big-mushroom': {
    id: 'big-mushroom',
    comment: '큰버섯',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 2500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'big-pearl': {
    id: 'big-pearl',
    comment: '큰진주',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 3750,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'rare-bone': {
    id: 'rare-bone',
    comment: '귀중한뼈',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 5000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  honey: {
    id: 'honey',
    comment: '달콤한꿀',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'pretty-wing': {
    id: 'pretty-wing',
    comment: '고운깃털',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'balm-mushroom': {
    id: 'balm-mushroom',
    comment: '향기버섯',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 6250,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'comet-shard': {
    id: 'comet-shard',
    comment: '혜성조각',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 15000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'big-nugget': {
    id: 'big-nugget',
    comment: '큰금구슬',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 10000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'pearl-string': {
    id: 'pearl-string',
    comment: '경단진주',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 7500,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-band': {
    id: 'relic-band',
    comment: '고대의팔찌',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 100000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-copper': {
    id: 'relic-copper',
    comment: '고대의동화',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1200,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-silver': {
    id: 'relic-silver',
    comment: '고대의은화',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 5000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-gold': {
    id: 'relic-gold',
    comment: '고대의금화',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 10000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-crown': {
    id: 'relic-crown',
    comment: '고대의왕관',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 300000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-statue': {
    id: 'relic-statue',
    comment: '고대의석상',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 200000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'relic-vase': {
    id: 'relic-vase',
    comment: '고대의항아리',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 50000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'ability-capsule': {
    id: 'ability-capsule',
    comment: '특성캡슐',
    type: ItemCategory.ETC,
    buyPrice: 10000,
    sellPrice: 3000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'ability-patch': {
    id: 'ability-patch',
    comment: '특성패치',
    type: ItemCategory.ETC,
    buyPrice: 12000,
    sellPrice: 4000,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'helix-fossil': {
    id: 'helix-fossil',
    comment: '조개화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'dome-fossil': {
    id: 'dome-fossil',
    comment: '껍질화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'old-amber': {
    id: 'old-amber',
    comment: '비밀의호박',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'root-fossil': {
    id: 'root-fossil',
    comment: '뿌리화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'claw-fossil': {
    id: 'claw-fossil',
    comment: '발톱화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'skull-fossil': {
    id: 'skull-fossil',
    comment: '두개의화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'armor-fossil': {
    id: 'armor-fossil',
    comment: '방패의화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'cover-fossil': {
    id: 'cover-fossil',
    comment: '덮개화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'plume-fossil': {
    id: 'plume-fossil',
    comment: '깃털화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'jaw-fossil': {
    id: 'jaw-fossil',
    comment: '턱화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'sail-fossil': {
    id: 'sail-fossil',
    comment: '지느러미화석',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'fossilized-bird': {
    id: 'fossilized-bird',
    comment: '화석새',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'fossilized-fish': {
    id: 'fossilized-fish',
    comment: '화석물고기',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'fossilized-drake': {
    id: 'fossilized-drake',
    comment: '화석용',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  'fossilized-dino': {
    id: 'fossilized-dino',
    comment: '화석긴목',
    type: ItemCategory.ETC,
    buyPrice: 999999999,
    sellPrice: 1000,
    purchasable: true,
    sellable: true,
    usable: false,
    registerable: false,
  },
  hm01: {
    id: 'hm01',
    comment: 'HM01:풀배기',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm02: {
    id: 'hm02',
    comment: 'HM02:공중날기',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm03: {
    id: 'hm03',
    comment: 'HM03:파도타기',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm04: {
    id: 'hm04',
    comment: 'HM04:괴력',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm05: {
    id: 'hm05',
    comment: 'HM05:플래시',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm06: {
    id: 'hm06',
    comment: 'HM06:바위깨기',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm07: {
    id: 'hm07',
    comment: 'HM07:폭포오르기',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  hm08: {
    id: 'hm08',
    comment: 'HM08:다이빙',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'tm-mean-look': {
    id: 'tm-mean-look',
    comment: 'TM01:검은눈빛',
    type: ItemCategory.TM_HM,
    buyPrice: 15000,
    sellPrice: 1500,
    purchasable: false,
    sellable: true,
    usable: true,
    registerable: false,
  },
  bicycle: {
    id: 'bicycle',
    comment: '자전거',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: true,
  },
  gracidea: {
    id: 'gracidea',
    comment: '그라시데아꽃',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'reveal-glass': {
    id: 'reveal-glass',
    comment: '비추는거울',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'dna-splicers': {
    id: 'dna-splicers',
    comment: '유전자쐐기',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'prison-bottle': {
    id: 'prison-bottle',
    comment: '굴레의항아리',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'n-lunarizer': {
    id: 'n-lunarizer',
    comment: '네크로플러스루나',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'n-solarizer': {
    id: 'n-solarizer',
    comment: '네크로플러스솔',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'red-nectar': {
    id: 'red-nectar',
    comment: '다홍꿀',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'purple-nectar': {
    id: 'purple-nectar',
    comment: '보라꿀',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'pink-nectar': {
    id: 'pink-nectar',
    comment: '연분홍꿀',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'yellow-nectar': {
    id: 'yellow-nectar',
    comment: '진노랑꿀',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'rusted-sword': {
    id: 'rusted-sword',
    comment: '녹슨검',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'rusted-shield': {
    id: 'rusted-shield',
    comment: '녹슨방패',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'rotom-catalog': {
    id: 'rotom-catalog',
    comment: '로토무카탈로그',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'reins-of-unity': {
    id: 'reins-of-unity',
    comment: '유대의고삐',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'adamant-crystal': {
    id: 'adamant-crystal',
    comment: '큰금강옥',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'lustrous-globe': {
    id: 'lustrous-globe',
    comment: '큰백옥',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'griseous-core': {
    id: 'griseous-core',
    comment: '큰백금옥',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'cornerstone-mask': {
    id: 'cornerstone-mask',
    comment: '주춧돌의가면',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'wellspring-mask': {
    id: 'wellspring-mask',
    comment: '우물의가면',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'hearthflame-mask': {
    id: 'hearthflame-mask',
    comment: '화덕의가면',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'red-orb': {
    id: 'red-orb',
    comment: '주홍구슬',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
  'blue-orb': {
    id: 'blue-orb',
    comment: '쪽빛구슬',
    type: ItemCategory.KEY,
    buyPrice: 999999999,
    sellPrice: 0,
    purchasable: true,
    sellable: true,
    usable: true,
    registerable: false,
  },
};

export const itemData = new Proxy(initialItemData, {
  get(target, key: string) {
    if (key in target) {
      return target[key];
    } else {
      console.warn(`Item '${key}' does not exist.`);
      return null;
    }
  },
});

export function getAllItems(): ItemData[] {
  return Object.values(initialItemData);
}

export function getItemByKey(key: string): ItemData | null {
  if (key in initialItemData) {
    return initialItemData[key];
  } else {
    console.warn(`Item with key '${key}' does not exist.`);
    return null;
  }
}

const initialNpcData: Record<string, NpcData> = {
  npc000: {
    movable: false,
  },
  npc001: {
    movable: false,
  },
  npc002: {
    movable: false,
  },
  npc003: {
    movable: false,
  },
  npc004: {
    movable: false,
  },
  npc005: {
    movable: false,
  },
  npc006: {
    movable: false,
  },
  npc007: {
    movable: false,
  },
  npc008: {
    movable: false,
  },
  npc009: {
    movable: false,
  },
  npc010: {
    movable: false,
  },
  npc011: {
    movable: false,
  },
  npc012: {
    movable: false,
  },
  npc013: {
    movable: false,
  },
  npc014: {
    movable: false,
  },
  npc015: {
    movable: false,
  },
  npc016: {
    movable: false,
  },
  npc017: {
    movable: false,
  },
  npc018: {
    movable: false,
  },
  npc019: {
    movable: false,
  },
  npc020: {
    movable: false,
  },
  npc021: {
    movable: false,
  },
  npc022: {
    movable: false,
  },
  npc023: {
    movable: false,
  },
  npc024: {
    movable: false,
  },
  npc025: {
    movable: false,
  },
  npc026: {
    movable: false,
  },
  npc027: {
    movable: false,
  },
  npc028: {
    movable: false,
  },
  npc029: {
    movable: false,
  },
};

export const npcData = new Proxy(initialNpcData, {
  get(target, key: string) {
    if (key in target) {
      return target[key];
    } else {
      console.warn(`Npc '${key}' does not exist.`);
      return null;
    }
  },
});

export interface PokemonData {
  offsetY: number;
  shadow: number;
  shadowOffsetX: number;
}

export const females = [3, 12, 19, 20, 25, 26, 41, 42, 44, 45, 64, 65, 84, 85, 97, 111, 112, 118, 119, 123, 129, 130];

export const PokemonData: Record<number, PokemonData> = {
  1: { offsetY: 30, shadow: 0, shadowOffsetX: 0 },
  2: { offsetY: -5, shadow: 1, shadowOffsetX: 0 },
  3: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  4: { offsetY: 0, shadow: 0, shadowOffsetX: -10 },
  5: { offsetY: -15, shadow: 1, shadowOffsetX: -15 },
  6: { offsetY: -55, shadow: 2, shadowOffsetX: 0 },
  7: { offsetY: 10, shadow: 0, shadowOffsetX: -5 },
  8: { offsetY: -25, shadow: 1, shadowOffsetX: -5 },
  9: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  10: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  11: { offsetY: +13, shadow: 0, shadowOffsetX: +10 },
  12: { offsetY: -60, shadow: 1, shadowOffsetX: 0 },
  13: { offsetY: +10, shadow: 0, shadowOffsetX: 0 },
  14: { offsetY: +10, shadow: 0, shadowOffsetX: 0 },
  15: { offsetY: -60, shadow: 1, shadowOffsetX: +10 },
  16: { offsetY: +10, shadow: 0, shadowOffsetX: 0 },
  17: { offsetY: -80, shadow: 1, shadowOffsetX: 0 },
  18: { offsetY: -30, shadow: 2, shadowOffsetX: -20 },
  19: { offsetY: +32, shadow: 1, shadowOffsetX: 0 },
  20: { offsetY: -5, shadow: 1, shadowOffsetX: +20 },
  21: { offsetY: +20, shadow: 0, shadowOffsetX: 0 },
  22: { offsetY: -65, shadow: 1, shadowOffsetX: 0 },
  23: { offsetY: +5, shadow: 1, shadowOffsetX: 0 },
  24: { offsetY: -30, shadow: 2, shadowOffsetX: 0 },
  25: { offsetY: 0, shadow: 0, shadowOffsetX: -15 },
  26: { offsetY: -15, shadow: 1, shadowOffsetX: -15 },
  27: { offsetY: +15, shadow: 0, shadowOffsetX: -5 },
  28: { offsetY: +5, shadow: 1, shadowOffsetX: 0 },
  29: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  30: { offsetY: +15, shadow: 1, shadowOffsetX: 0 },
  31: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  32: { offsetY: +25, shadow: 0, shadowOffsetX: 0 },
  33: { offsetY: +5, shadow: 1, shadowOffsetX: 0 },
  34: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  35: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  36: { offsetY: -20, shadow: 1, shadowOffsetX: 0 },
  37: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  38: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  39: { offsetY: +15, shadow: 0, shadowOffsetX: +10 },
  40: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  41: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  42: { offsetY: -55, shadow: 1, shadowOffsetX: 0 },
  43: { offsetY: +10, shadow: 0, shadowOffsetX: -10 },
  44: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  45: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  46: { offsetY: +50, shadow: 1, shadowOffsetX: -20 },
  47: { offsetY: +10, shadow: 2, shadowOffsetX: 0 },
  48: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  49: { offsetY: -45, shadow: 0, shadowOffsetX: 0 },
  50: { offsetY: +35, shadow: 0, shadowOffsetX: 0 },
  51: { offsetY: +15, shadow: 0, shadowOffsetX: 0 },
  52: { offsetY: -5, shadow: 1, shadowOffsetX: 0 },
  53: { offsetY: -30, shadow: 2, shadowOffsetX: +30 },
  54: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  55: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  56: { offsetY: -5, shadow: 1, shadowOffsetX: +10 },
  57: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  58: { offsetY: +15, shadow: 1, shadowOffsetX: 0 },
  59: { offsetY: -40, shadow: 2, shadowOffsetX: 0 },
  60: { offsetY: +10, shadow: 0, shadowOffsetX: -10 },
  61: { offsetY: 0, shadow: 1, shadowOffsetX: 0 },
  62: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  63: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  64: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  65: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  66: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  67: { offsetY: -50, shadow: 1, shadowOffsetX: 0 },
  68: { offsetY: -45, shadow: 2, shadowOffsetX: 0 },
  69: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  70: { offsetY: +15, shadow: 1, shadowOffsetX: -30 },
  71: { offsetY: +5, shadow: 2, shadowOffsetX: 0 },
  72: { offsetY: -25, shadow: 1, shadowOffsetX: 0 },
  73: { offsetY: -25, shadow: 2, shadowOffsetX: 0 },
  74: { offsetY: +35, shadow: 1, shadowOffsetX: +10 },
  75: { offsetY: +5, shadow: 1, shadowOffsetX: 0 },
  76: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  77: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  78: { offsetY: -45, shadow: 2, shadowOffsetX: 0 },
  79: { offsetY: 0, shadow: 2, shadowOffsetX: 0 },
  80: { offsetY: -30, shadow: 2, shadowOffsetX: 0 },
  81: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  82: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  83: { offsetY: -10, shadow: 0, shadowOffsetX: 0 },
  84: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  85: { offsetY: -40, shadow: 1, shadowOffsetX: 0 },
  86: { offsetY: -10, shadow: 1, shadowOffsetX: 0 },
  87: { offsetY: -45, shadow: 2, shadowOffsetX: 0 },
  88: { offsetY: +20, shadow: 1, shadowOffsetX: 0 },
  89: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  90: { offsetY: +20, shadow: 0, shadowOffsetX: 0 },
  91: { offsetY: -20, shadow: 2, shadowOffsetX: 0 },
  92: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  93: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  94: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  95: { offsetY: -45, shadow: 1, shadowOffsetX: +20 },
  96: { offsetY: -15, shadow: 1, shadowOffsetX: +20 },
  97: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  98: { offsetY: +15, shadow: 0, shadowOffsetX: 0 },
  99: { offsetY: -15, shadow: 2, shadowOffsetX: 0 },
  100: { offsetY: +25, shadow: 0, shadowOffsetX: 0 },
  101: { offsetY: -10, shadow: 0, shadowOffsetX: 0 },
  102: { offsetY: +15, shadow: 1, shadowOffsetX: 0 },
  103: { offsetY: -55, shadow: 1, shadowOffsetX: 0 },
  104: { offsetY: +15, shadow: 0, shadowOffsetX: 0 },
  105: { offsetY: +5, shadow: 1, shadowOffsetX: +30 },
  106: { offsetY: -35, shadow: 0, shadowOffsetX: 0 },
  107: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  108: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  109: { offsetY: -25, shadow: 0, shadowOffsetX: 0 },
  110: { offsetY: -35, shadow: 1, shadowOffsetX: 0 },
  111: { offsetY: +5, shadow: 2, shadowOffsetX: 0 },
  112: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  113: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  114: { offsetY: +5, shadow: 0, shadowOffsetX: 0 },
  115: { offsetY: -25, shadow: 2, shadowOffsetX: 0 },
  116: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  117: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  118: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  119: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  120: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  121: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  122: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  123: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  124: { offsetY: -5, shadow: 2, shadowOffsetX: 0 },
  125: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  126: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  127: { offsetY: -15, shadow: 1, shadowOffsetX: 0 },
  128: { offsetY: -10, shadow: 2, shadowOffsetX: +35 },
  129: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  130: { offsetY: -25, shadow: 2, shadowOffsetX: 0 },
  131: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  132: { offsetY: +35, shadow: 1, shadowOffsetX: 0 },
  133: { offsetY: +15, shadow: 0, shadowOffsetX: 0 },
  134: { offsetY: -10, shadow: 1, shadowOffsetX: -10 },
  135: { offsetY: +5, shadow: 1, shadowOffsetX: +10 },
  136: { offsetY: -5, shadow: 1, shadowOffsetX: -10 },
  137: { offsetY: -15, shadow: 0, shadowOffsetX: 0 },
  138: { offsetY: +15, shadow: 0, shadowOffsetX: 0 },
  139: { offsetY: -5, shadow: 1, shadowOffsetX: 0 },
  140: { offsetY: +25, shadow: 0, shadowOffsetX: +5 },
  141: { offsetY: -15, shadow: 1, shadowOffsetX: +20 },
  142: { offsetY: -65, shadow: 1, shadowOffsetX: +10 },
  143: { offsetY: -45, shadow: 2, shadowOffsetX: 0 },
  144: { offsetY: -55, shadow: 2, shadowOffsetX: -25 },
  145: { offsetY: -65, shadow: 2, shadowOffsetX: 0 },
  146: { offsetY: -65, shadow: 2, shadowOffsetX: -25 },
  147: { offsetY: +5, shadow: 0, shadowOffsetX: +10 },
  148: { offsetY: -35, shadow: 2, shadowOffsetX: 0 },
  149: { offsetY: -45, shadow: 2, shadowOffsetX: -30 },
  150: { offsetY: -45, shadow: 2, shadowOffsetX: 0 },
  151: { offsetY: -35, shadow: 0, shadowOffsetX: 0 },
};

export function getPokemonInfo(pokedexNumber: number): PokemonData | null {
  const info = PokemonData[pokedexNumber];
  if (!info) {
    console.warn(`not found Pokemon`);
    return null;
  }
  return info;
}

export interface SafariData {
  key: string;
  area: BATTLE_AREA;
}

const initialSafariData: Record<string, SafariData> = {
  s001: {
    key: 's001',
    area: BATTLE_AREA.FIELD,
  },
  s002: {
    key: 's002',
    area: BATTLE_AREA.FIELD,
  },
};

export function getAllSafaris(): SafariData[] {
  return Object.values(initialSafariData);
}
export function getSafariByKey(key: string): SafariData | null {
  if (key in initialSafariData) {
    return initialSafariData[key];
  } else {
    console.warn(`Item with key '${key}' does not exist.`);
    return null;
  }
}
